### ISSUE TITLE
Add --usher mode assignments in addition

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pangolin-assignment#1]
It would be great if --usher mode assignments were also published here

**Comment by AngieHinrichs** [comment]
They are here!  :)  Ongoing testing with the pangolin handle_cache branch which will hopefully soon become a v4.0 prerelease.

**Comment by corneliusroemer** [comment]
Nice! They are not with EPI_ISL or clear text but hashed now, correct?

**Comment by AngieHinrichs** [comment]
Yes, using the same hash that pangolin uses for its designated sequence hash.

pangolin aligns each sequence to a lineage A reference (not NC_045512.2 Wuhan/Hu-1 like most tools) and then masks the untranslated regions at the beginning and end of the aligned sequence.  Then it's the md5sum of that (uppercase) aligned and masked sequence.  Alignment and masking brings the number of unique sequences down from ~9M to ~7M.
